### ISSUE TITLE
Respawn duplicates items

### ISSUE THREAD

**Issue by EMPFingers** [Cyanox62/DCReplace#4]
Kicking/banning a player or them leaving the game will cause their items to drop on the ground, plugin will then spawn the new player in with all the items the individual disconnecting had as well as the items on the ground.

https://streamable.com/ki3ig6

This could be resolved by setting `disconnect_drop: false` in the config_gameplay, but I figured I'd mention it here if you want to address it by having it override when the plugin is in the server or something.

**Comment by Cyanox62** [comment]
I've handled this issue beforehand, but I should mention it. I'll add it into the readme.
