### ISSUE TITLE
nice joke

### ISSUE THREAD

**Issue by PUDGE133** [Cyanox62/DCReplace#7]
I once added your plugin a long time ago and forgot to configure it. Then I started noticing his activity on the server. I remembered that it needs to be configured. But I couldn't do it because I just couldn't find it in the config. I have been looking for settings for your plugin for a very long time. Then I got tired and put the matter aside. And then the next day, when I was setting up another plugin, I accidentally discovered the settings for yours.
```yaml
dc_replace:
  is_enabled: true
```
What the fuck is this? Ahahahahahah excuse me. But I can not. I just can't help but ask this question. What the fuck is this? When I discovered this, I almost fell out of my chair laughing.

**Comment by PintTheDragon** [comment]
This might go over your head, but sometimes server hosts like to host more than one server, and sometimes might want to have different plugins on their servers.

Why did you even make an issue about this? Does the fact that you can turn off a plugin seem so bad to you that you went out of your way to write this? I just don't understand.

**Comment by PUDGE133** [comment]
> This might go over your head, but sometimes server hosts like to host more than one server, and sometimes might want to have different plugins on their servers.
> 
> Why did you even make an issue about this? Does the fact that you can turn off a plugin seem so bad to you that you went out of your way to write this? I just don't understand.

Do you need to have 100 points in the iq test to understand that there is clearly no configuration here? Are you aware that this plugin has, for example, broadcast messages that I NEED TO CONFIGURE?
Why the fuck publish a plugin that doesn't even have a configuration? I am amazed at questions like yours. Just turn on both convolutions in your head and such stupid questions will disappear by themselves. And I'm not trying to offend you or the author. But do you really need to have 100 points in the iq test to understand what I'm saying?

**Comment by PUDGE133** [comment]
> This might go over your head, but sometimes server hosts like to host more than one server, and sometimes might want to have different plugins on their servers.
> 
> Why did you even make an issue about this? Does the fact that you can turn off a plugin seem so bad to you that you went out of your way to write this? I just don't understand.

This might go over your head, but sometimes server hosts choose to configure plugins on their servers.

Why did you even make an issue about this? Does the fact that you can't customize the plugin seem so good to you that you've tried your best to write it? I just do not understand.

How is it? Did I manage to convey the stupidity of your question in this comment?

**Comment by Kade-github** [comment]
> > This might go over your head, but sometimes server hosts like to host more than one server, and sometimes might want to have different plugins on their servers.
> > Why did you even make an issue about this? Does the fact that you can turn off a plugin seem so bad to you that you went out of your way to write this? I just don't understand.
> 
> This might go over your head, but sometimes server hosts choose to configure plugins on their servers.
> 
> Why did you even make an issue about this? Does the fact that you can't customize the plugin seem so good to you that you've tried your best to write it? I just do not understand.
> 
> How is it? Did I manage to convey the stupidity of your question in this comment?

write a better one then dipshit, no wonder you are banned for the Exiled Discord Server.
mega wall-of-shame moment.

**Comment by PUDGE133** [comment]
> write a better one then dipshit, no wonder you are banned for the Exiled Discord Server.
> mega wall-of-shame moment.

I saw 0% helpful information in your comment.

Typical reaction of any idiot to adequate criticism. "Do it yourself first, then criticize." This is the mindset of an idiot. Obviously, I don't have to be a cameraman or director to say that a film is bad. I don't have to be a chef to say the food isn't tasty. Obviously, I don't have to be a programmer to say that a this plugin is openly little-functional crap that cannot be configured in any way.

I got banned in "exiled" for racism towards myself. No matter how crazy it sounds.
I want to ask you a question. Are you in charge of everyone who makes plugins? It seems I wrote this to that programmer personally, not to you. Take responsibility for yourself, not for others. When the questions reach you, you will answer. But there are no questions for you and your plugins yet, because even such a degenerate as you guessed that creating a plugin for the public should be given the opportunity to customize it.

**Comment by PintTheDragon** [comment]
Oh lmao I thought you were complaining about is_enabled existing for some reason. How about you close this issue, then make a new one titled "Add more config options" and list some examples like the messages sent to people.

**Comment by PUDGE133** [comment]
> Oh lmao I thought you were complaining about is_enabled existing for some reason. How about you close this issue, then make a new one titled "Add more config options" and list some examples like the messages sent to people.

I have no words. No, I really have no words. I sat for 2 minutes and did not understand where there are so many idiots on this planet.
1. That is, of all the idiots who used this plug-in before me, they did not even think that something was wrong with it?
2. Isn't it possible to just turn on the brain and understand that people need to configure it somehow before publishing a plugin?

No, I really have no words. And I come across such idiocy in NW, SCPSL and EXILED 4-5 times a month.
Do the obvious things SHOULD BE EXPLAINED? That is, you need to have 100 points in the iq test to understand that before publishing a plugin, you need to give people the opportunity to customize it?
For some reason, you guessed to make a setting in your plugins. So I have never written a bad word to you.
My ass is really, unrealistically, burning from total idiocy. I can't help but offend idiots, which is why I'm in the EXILED bath (I insulted myself). People don't like to read / listen to the truth.

**Comment by PintTheDragon** [comment]
You came here and did nothing but complain and insult people. You didn't even explicitly state what the issue was in your issue, you just decided to insult people (to a point where I wasn't able to figure out what your problem actually was). If you want something changed, then either change it yourself or make an actual issue that says exactly what you want to be changed. I don't know what you think insulting people will do.

**Comment by Danstr5544** [comment]
Folks, let's chill. I'm not your parent, but Jesus Christ...
@Tamago4a For most, provided a plugin functions, they don't really mind if it doesn't have a few things. They're called consumers, not idea makers. You make a fair point, but this issue is soured by this arguement, make a NEW issue and keep it friendly.

**Comment by AgentBlackout** [comment]
> > Oh lmao I thought you were complaining about is_enabled existing for some reason. How about you close this issue, then make a new one titled "Add more config options" and list some examples like the messages sent to people.
> 
> I have no words. No, I really have no words. I sat for 2 minutes and did not understand where there are so many idiots on this planet.
> 
> 1. That is, of all the idiots who used this plug-in before me, they did not even think that something was wrong with it?
> 2. Isn't it possible to just turn on the brain and understand that people need to configure it somehow before publishing a plugin?
> 
> No, I really have no words. And I come across such idiocy in NW, SCPSL and EXILED 4-5 times a month.
> Do the obvious things SHOULD BE EXPLAINED? That is, you need to have 100 points in the iq test to understand that before publishing a plugin, you need to give people the opportunity to customize it?
> For some reason, you guessed to make a setting in your plugins. So I have never written a bad word to you.
> My ass is really, unrealistically, burning from total idiocy. I can't help but offend idiots, which is why I'm in the EXILED bath (I insulted myself). People don't like to read / listen to the truth.

Begone thot. Thou art not welcome here

**Comment by Cyanox62** [comment]
How about rather than talking shit on something I created you be appreciative for once? People spend hundreds of hours making public plugins to better the community. I have absolutely no obligation to create anything for you, nor do any of the other devs.  You are unbelievably immature and frankly pathetic to attack those working to benefit you who receive nothing in return. The world doesn't revolve around you. Quit being so fucking entitled and show some respect for the people working to actively benefit your server and many more.

**Comment by EsserGaming** [comment]
Well, you abandoned the project, so what are we supposed to think about it now?

**Comment by PUDGE133** [comment]
> Well, you abandoned the project, so what are we supposed to think about it now?

I recommend not using this plugin. Its author never added the normal configuration. The plugin has bugs not finalized, as well as it is not very functional.

**Comment by EsserGaming** [comment]
You're a joke, the config is fine and it works just fine, with a few bugs here and there.

**Comment by PUDGE133** [comment]
> You're a joke, the config is fine and it works just fine, with a few bugs here and there.

DCReplace v1.1.0 (Exiled 2.0)
Cyanox62 released this on 18 Sep 2020

Tamago4a opened this issue on 25 Nov 2020

Lift your eyes higher and you will see there information that the configuration is missing.
```yaml
dc_replace:
  is_enabled: true
```

**Comment by EsserGaming** [comment]
Bro, do you code? no. stop, if you do make your own fork and remove that because you are the only one who is so mad about it.

**Comment by PUDGE133** [comment]
> Bro, do you code? no. stop, if you do make your own fork and remove that because you are the only one who is so mad about it.

I probably don't need to be the director of the film or the cameraman or the actor to understand that the movie sucked?

**Comment by EsserGaming** [comment]
You're putting a obvious red herring up, you know I'm right.

**Comment by AgentBlackout** [comment]
Autism

**Comment by PUDGE133** [comment]
> Autism

But in order to make diagnoses, you need to have a medical education. Here the scheme about cinema described above does not work.
